# Generated by Django 5.1.5 on 2026-03-12 09:38

import apps.transformation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('source', 'Source File'), ('canvas', 'Canvas File')], db_index=True, max_length=10)),
                ('file', models.FileField(upload_to=apps.transformation.models.upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('xlsx', 'Excel (xlsx)'), ('xls', 'Excel 97-2003 (xls)'), ('csv', 'CSV')], max_length=10)),
                ('headers_json', models.JSONField(default=list, help_text='Extracted column headers')),
                ('field_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
