# Generated by Django 5.1.5 on 2026-03-12 10:00

import apps.transformation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.transformation.models.upload_path),
        ),
    ]
