# Generated by Django 5.1.5 on 2026-03-12 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0002_no_file_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Package display name', max_length=255)),
                ('file_pattern', models.CharField(help_text='Glob pattern for matching inbound files, e.g. MBB_*.csv', max_length=255)),
                ('input_format', models.CharField(choices=[('xlsx', 'Excel (xlsx)'), ('xls', 'Excel 97-2003 (xls)'), ('csv', 'CSV')], default='csv', help_text='Expected format of inbound source files', max_length=10)),
                ('output_format', models.CharField(choices=[('xlsx', 'Excel (xlsx)'), ('xls', 'Excel 97-2003 (xls)'), ('csv', 'CSV')], default='csv', help_text='Format of the transformed output file', max_length=10)),
                ('output_prefix', models.CharField(help_text='Prefix for output filename, e.g. mbbprocess_', max_length=255)),
                ('batch_mode', models.CharField(choices=[('instant', 'Instant (File Sense)'), ('scheduled', 'Scheduled')], default='instant', max_length=10)),
                ('batch_interval_minutes', models.PositiveIntegerField(default=0, help_text='Interval in minutes (1–1440) when batch_mode is scheduled')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('running', 'Running'), ('paused', 'Paused')], db_index=True, default='inactive', max_length=10)),
                ('mapping_status', models.CharField(choices=[('unmapped', 'Unmapped'), ('mapped', 'Mapped')], db_index=True, default='unmapped', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas_file', models.ForeignKey(help_text='Canvas file whose headers define the output schema', limit_choices_to={'file_type': 'canvas'}, on_delete=django.db.models.deletion.PROTECT, related_name='packages_as_canvas', to='transformation.uploadedfile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(help_text='Source file whose headers define the input schema', limit_choices_to={'file_type': 'source'}, on_delete=django.db.models.deletion.PROTECT, related_name='packages_as_source', to='transformation.uploadedfile')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_header', models.CharField(help_text='Column from source file', max_length=255)),
                ('canvas_header', models.CharField(help_text='Column from canvas file', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display/export order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='transformation.package')),
            ],
            options={
                'verbose_name': 'Field Mapping',
                'verbose_name_plural': 'Field Mappings',
                'ordering': ['order'],
                'unique_together': {('package', 'canvas_header')},
            },
        ),
    ]
