# Generated by Django 5.1.5 on 2026-03-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0003_package_fieldmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmapping',
            name='condition_json',
            field=models.JSONField(blank=True, default=None, help_text='Structured condition rules. Example:\n        {\n            "condition_type": "if_else",\n            "source_field": "Debit (DR)",\n            "operator": ">",\n            "compare_value": "0",\n            "then_source": "Debit (DR)",\n            "else_source": "Credit (CR)"\n        }\n        Operators: >, <, >=, <=, ==, !=, contains, not_empty, is_empty', null=True),
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='constant_value',
            field=models.CharField(blank=True, default='', help_text='Fixed value to output when mapping_type is constant', max_length=500),
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='has_condition',
            field=models.BooleanField(default=False, help_text='Toggle: enable conditional logic for this mapping'),
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='mapping_type',
            field=models.CharField(choices=[('direct', 'Direct Mapping'), ('condition', 'Conditional (IF/ELSE)'), ('constant', 'Constant Value')], default='direct', max_length=10),
        ),
        migrations.AlterField(
            model_name='fieldmapping',
            name='source_header',
            field=models.CharField(blank=True, default='', help_text='Column from source file (used for direct mapping)', max_length=255),
        ),
    ]
