# Generated by Django 5.1.5 on 2026-03-12 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0004_fieldmapping_condition_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundFileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=500)),
                ('file_content', models.BinaryField(help_text='Raw binary content of the processed inbound file')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('file_format', models.CharField(default='csv', max_length=10)),
                ('output_filename', models.CharField(blank=True, default='', help_text='Name of the generated output file in trfm_outbound', max_length=500)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_logs', to='transformation.package')),
            ],
            options={
                'verbose_name': 'Inbound File Log',
                'verbose_name_plural': 'Inbound File Logs',
                'ordering': ['-processed_at'],
            },
        ),
    ]
