# Generated by Django 5.1.5 on 2026-03-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0005_inboundfilelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundfilelog',
            name='run_type',
            field=models.CharField(choices=[('instant', 'Instant (File Sense)'), ('scheduled', 'Scheduled (Batch)'), ('adhoc', 'Ad-hoc (Manual)')], default='instant', help_text='How the run was triggered: instant (file sense), scheduled (batch), adhoc (manual)', max_length=10),
        ),
    ]
