# Generated by Django 5.1.5 on 2026-03-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0006_inboundfilelog_run_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#40c4ff', help_text='Hex colour code for the tag chip', max_length=7)),
                ('auto_created', models.BooleanField(default=False, help_text='True if the tag was generated automatically by the system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'File Tag',
                'verbose_name_plural': 'File Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inboundfilelog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='file_logs', to='transformation.filetag'),
        ),
    ]
