# Generated by Django 5.1.5 on 2026-03-15 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0007_filetag_inboundfilelog_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiftParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MT', 'MT (FIN)'), ('MX', 'MX (ISO 20022)'), ('BIC', 'BIC Codes'), ('TRAD', 'Trade'), ('GENERAL', 'General')], db_index=True, help_text='Parameter category: MT, MX, BIC, TRAD, or GENERAL', max_length=10)),
                ('message_type', models.CharField(db_index=True, help_text='Message type, e.g. MT103, MT540, pacs.008, camt.053', max_length=30)),
                ('field_tag', models.CharField(help_text='SWIFT field tag, e.g. :20:, :32A:, :50K:, MsgId, BIC', max_length=30)),
                ('field_name', models.CharField(help_text='Human-readable name, e.g. Transaction Reference', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the field purpose and usage')),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('AMOUNT', 'Amount'), ('DATE', 'Date'), ('DATETIME', 'Date/Time'), ('BIC', 'BIC Code'), ('ACCOUNT', 'Account Number'), ('CURRENCY', 'Currency Code'), ('CODE', 'Code/Indicator'), ('NARRATIVE', 'Narrative/Free Text'), ('QUANTITY', 'Quantity'), ('RATE', 'Rate/Price'), ('ISIN', 'ISIN Code'), ('REFERENCE', 'Reference')], default='TEXT', max_length=12)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Whether this field is mandatory in the message')),
                ('max_length', models.PositiveIntegerField(blank=True, help_text='Maximum allowed characters', null=True)),
                ('format_pattern', models.CharField(blank=True, default='', help_text='Format notation, e.g. 16x, 6!n, 3!a15d, //YYYY-MM-DD', max_length=100)),
                ('sample_value', models.CharField(blank=True, default='', help_text='Example value for reference', max_length=255)),
                ('options_json', models.JSONField(blank=True, default=dict, help_text='Additional metadata: allowed_values, sub_fields, qualifiers, etc.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swift_parameters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SWIFT Parameter',
                'verbose_name_plural': 'SWIFT Parameters',
                'ordering': ['category', 'message_type', 'field_tag'],
                'unique_together': {('category', 'message_type', 'field_tag')},
            },
        ),
    ]
