# Generated by Django 5.1.5 on 2026-03-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0008_swift_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiftparameter',
            name='category',
            field=models.CharField(choices=[('MT', 'MT (FIN)'), ('MX', 'MX (ISO 20022)'), ('BIC', 'BIC Codes'), ('GENERAL', 'General')], db_index=True, help_text='Parameter category: MT, MX, BIC, TRAD, or GENERAL', max_length=10),
        ),
    ]
