# Generated by Django 5.1.5 on 2026-03-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0009_remove_trad_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiftMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(help_text='e.g. MT541', max_length=10)),
                ('message_type_description', models.CharField(blank=True, default='', max_length=200)),
                ('sender_bic', models.CharField(blank=True, default='', max_length=12)),
                ('receiver_bic', models.CharField(blank=True, default='', max_length=12)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('raw_content', models.TextField(help_text='Full original message text')),
                ('parsed_json', models.JSONField(blank=True, default=dict, help_text='Structured parsed fields')),
                ('original_filename', models.CharField(max_length=255)),
                ('excel_filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_file_content', models.BinaryField(blank=True, help_text='Raw file bytes', null=True)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('failed', 'Failed')], default='processed', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SWIFT Message',
                'verbose_name_plural': 'SWIFT Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
