# Generated by Django 5.1.5 on 2026-03-15 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0010_swift_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundfilelog',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_logs', to='transformation.package'),
        ),
        migrations.AlterField(
            model_name='inboundfilelog',
            name='run_type',
            field=models.CharField(choices=[('instant', 'Instant (File Sense)'), ('scheduled', 'Scheduled (Batch)'), ('adhoc', 'Ad-hoc (Manual)'), ('swift', 'SWIFT Message')], default='instant', help_text='How the run was triggered: instant (file sense), scheduled (batch), adhoc (manual), swift (SWIFT message)', max_length=10),
        ),
    ]
