# Generated by Django 5.1.5 on 2026-03-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0011_swift_inbound_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiftPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('message_types', models.JSONField(default=list, help_text='List of MT/MX types to process, e.g. ["MT103","pacs.008"] or ["ALL"]')),
                ('output_format', models.CharField(choices=[('xlsx', 'Excel (XLSX)'), ('csv', 'CSV'), ('json', 'JSON')], default='xlsx', max_length=5)),
                ('processing_mode', models.CharField(choices=[('instant', 'Instant (File Sense)'), ('batch', 'Batch (Scheduled)')], default='instant', max_length=10)),
                ('file_pattern', models.CharField(default='*.*', help_text='Glob pattern for sft_inbound file matching, e.g. *.fin, *.xml', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SWIFT Package',
                'verbose_name_plural': 'SWIFT Packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
