# Generated by Django 5.1.5 on 2026-03-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0012_swift_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='swiftpackage',
            name='batch_interval_minutes',
            field=models.IntegerField(default=30, help_text='Interval in minutes for batch processing (only used when processing_mode=batch)'),
        ),
    ]
