# Generated by Django 5.1.5 on 2026-03-16 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0013_swiftpackage_batch_interval_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiftpackage',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('running', 'Running'), ('paused', 'Paused')], default='active', max_length=10),
        ),
        migrations.CreateModel(
            name='SwiftRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=500)),
                ('output_filename', models.CharField(blank=True, default='', max_length=500)),
                ('message_type', models.CharField(blank=True, default='', max_length=30)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('messages_processed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('run_type', models.CharField(choices=[('instant', 'Instant (File Sense)'), ('batch', 'Batch (Scheduled)'), ('manual', 'Manual (Ad-hoc)')], default='instant', max_length=10)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('swift_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='transformation.swiftpackage')),
            ],
            options={
                'verbose_name': 'SWIFT Run Log',
                'verbose_name_plural': 'SWIFT Run Logs',
                'ordering': ['-processed_at'],
            },
        ),
    ]
