# Generated by Django 5.1.5 on 2026-04-14 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0014_swift_run_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='filename_mode',
            field=models.CharField(choices=[('original', 'Keep Original Filename'), ('prefix', 'Prefix + Timestamp')], default='prefix', help_text='Output filename strategy: keep original or generate prefix+timestamp', max_length=10),
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('passthrough', 'Passthrough'), ('convert', 'Passthrough & Convert'), ('transformation', 'Transformation')], db_index=True, default='transformation', help_text='Processing mode: passthrough, convert, or transformation', max_length=15),
        ),
        migrations.AlterField(
            model_name='package',
            name='canvas_file',
            field=models.ForeignKey(blank=True, help_text='Canvas file whose headers define the output schema (transformation only)', limit_choices_to={'file_type': 'canvas'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages_as_canvas', to='transformation.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='package',
            name='output_prefix',
            field=models.CharField(blank=True, default='', help_text='Prefix for output filename (used when filename_mode=prefix)', max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='source_file',
            field=models.ForeignKey(blank=True, help_text='Source file whose headers define the input schema (transformation only)', limit_choices_to={'file_type': 'source'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages_as_source', to='transformation.uploadedfile'),
        ),
        migrations.CreateModel(
            name='DirectoryRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Directory name, e.g. maybank, imatch', max_length=100)),
                ('dir_type', models.CharField(choices=[('pool', 'Pool (Inbound/Outbound Pair)'), ('delivery', 'Delivery Target (Outbound Only)')], db_index=True, max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='True for system defaults like imatch/mpower')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Directory',
                'verbose_name_plural': 'Directories',
                'ordering': ['dir_type', 'name'],
                'unique_together': {('name', 'dir_type')},
            },
        ),
        migrations.AddField(
            model_name='package',
            name='delivery_directory',
            field=models.ForeignKey(blank=True, help_text='Final delivery target in trfm_outbound (e.g. imatch, mpower)', limit_choices_to={'dir_type': 'delivery'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_delivery', to='transformation.directoryregistry'),
        ),
        migrations.AddField(
            model_name='package',
            name='pool_directory',
            field=models.ForeignKey(blank=True, help_text='Pool directory in trfm_inbound to monitor (null = root)', limit_choices_to={'dir_type': 'pool'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_pool', to='transformation.directoryregistry'),
        ),
    ]
