# Generated by Django 5.1.5 on 2026-04-14 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0015_package_types_directory_registry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='swiftpackage',
            name='delivery_env',
            field=models.CharField(choices=[('dev', 'Development'), ('staging', 'Staging'), ('live', 'Live')], default='dev', help_text='Target environment for output delivery', max_length=10),
        ),
        migrations.CreateModel(
            name='SwiftDirectoryRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Directory name, e.g. imatch, mpower, bloomberg', max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='True for system defaults like imatch/mpower')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swift_directories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SWIFT Directory',
                'verbose_name_plural': 'SWIFT Directories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='swiftpackage',
            name='delivery_target',
            field=models.ForeignKey(blank=True, help_text='Delivery sub-directory (e.g. imatch, mpower)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swift_packages', to='transformation.swiftdirectoryregistry'),
        ),
    ]
